# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rc < Formula
  desc "RevenueCat command line interface"
  homepage "https://www.revenuecat.com"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RevenueCat/cli/releases/download/v0.1.1/rc_0.1.1_darwin_amd64.tar.gz"
      sha256 "a51b11e9cf1f30ebdff44b3fceabdee3f3e6752f72f927d97eba532b720ceb79"

      define_method(:install) do
        bin.install "rc"
        bin.install_symlink "rc" => "revenuecat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RevenueCat/cli/releases/download/v0.1.1/rc_0.1.1_darwin_arm64.tar.gz"
      sha256 "cf40ee6972b89ce919673dbcc45dbf98acc6bad601272437f6767cff6c907f37"

      define_method(:install) do
        bin.install "rc"
        bin.install_symlink "rc" => "revenuecat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RevenueCat/cli/releases/download/v0.1.1/rc_0.1.1_linux_amd64.tar.gz"
      sha256 "68b9eab06ec2f7ab0fa2af480ca71746c4472c30e7a44ca41970e1a4d1b40bc8"
      define_method(:install) do
        bin.install "rc"
        bin.install_symlink "rc" => "revenuecat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RevenueCat/cli/releases/download/v0.1.1/rc_0.1.1_linux_arm64.tar.gz"
      sha256 "c6ba534c43b0f6f47c7f1b8c565c403f54d0c7593f3cfacf78202e6e75fb5296"
      define_method(:install) do
        bin.install "rc"
        bin.install_symlink "rc" => "revenuecat"
      end
    end
  end

  test do
    system "#{bin}/rc", "--version"
    system "#{bin}/revenuecat", "--version"
  end
end
